version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: |
            git submodule add https://github.com/rhazdon/hugo-theme-hello-friend-ng.git themes/hello-friend-ng 
            hugo -D
            ls -la
            ls themes
            ls  themes/*
      - run:
          name: "Update Website"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then  
              git config --global user.email "turgayh@itu.edu.tr"
              git config --global user.name "turgayh"
              cd ./public
              git add .
              git commit -m "Circle CI Update Website | Build Number:${CIRCLE_BUILD_NUM}"
              git push -q https://${DEPLOY_KEY}@github.com/turgayh/turgayh.github.io.git master
              
            fi
